# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesktop1_Kopie.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1444, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(43, 31, 91);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"border-bottom: 1px solid #000;\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle.setStyleSheet("\n"
"QFrame{\n"
"background-color:#000;\n"
"}\n"
"\n"
"QPushButton{\n"
"padding:5px 10px;\n"
"border:none;\n"
"border-radius: 5px;\n"
"background-color:#000;\n"
"color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_menu_toggle_btn = QtWidgets.QPushButton(self.left_menu_toggle)
        self.left_menu_toggle_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.left_menu_toggle_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.left_menu_toggle_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.left_menu_toggle_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_menu_toggle_btn.setIcon(icon)
        self.left_menu_toggle_btn.setIconSize(QtCore.QSize(24, 24))
        self.left_menu_toggle_btn.setObjectName("left_menu_toggle_btn")
        self.horizontalLayout_4.addWidget(self.left_menu_toggle_btn)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.tittle_bar = QtWidgets.QFrame(self.tittle_bar_container)
        self.tittle_bar.setStyleSheet("\n"
"QFrame{\n"
"background-color:#000;\n"
"}\n"
"\n"
"QPushButton{\n"
"padding:5px 10px;\n"
"border:none;\n"
"border-radius: 5px;\n"
"background-color:#000;\n"
"color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.tittle_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.tittle_bar)
        self.gridLayout.setContentsMargins(12, -1, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.browse_files = QtWidgets.QPushButton(self.tittle_bar)
        self.browse_files.setMaximumSize(QtCore.QSize(60, 58))
        self.browse_files.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_files.setMouseTracking(False)
        self.browse_files.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_files.setIcon(icon1)
        self.browse_files.setIconSize(QtCore.QSize(24, 24))
        self.browse_files.setObjectName("browse_files")
        self.gridLayout.addWidget(self.browse_files, 0, 0, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.tittle_bar)
        self.playButton.setMaximumSize(QtCore.QSize(60, 62))
        self.playButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon2)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 0, 1, 1, 1)
        self.startRecorder = QtWidgets.QPushButton(self.tittle_bar)
        self.startRecorder.setMaximumSize(QtCore.QSize(60, 56))
        self.startRecorder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startRecorder.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startRecorder.setIcon(icon3)
        self.startRecorder.setIconSize(QtCore.QSize(24, 24))
        self.startRecorder.setObjectName("startRecorder")
        self.gridLayout.addWidget(self.startRecorder, 0, 2, 1, 1)
        self.rotation = QtWidgets.QPushButton(self.tittle_bar)
        self.rotation.setMaximumSize(QtCore.QSize(60, 57))
        self.rotation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rotation.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-loop-circular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotation.setIcon(icon4)
        self.rotation.setIconSize(QtCore.QSize(24, 24))
        self.rotation.setObjectName("rotation")
        self.gridLayout.addWidget(self.rotation, 0, 3, 1, 1)
        self.ImageCapture = QtWidgets.QPushButton(self.tittle_bar)
        self.ImageCapture.setMaximumSize(QtCore.QSize(60, 57))
        self.ImageCapture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ImageCapture.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cil-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImageCapture.setIcon(icon5)
        self.ImageCapture.setIconSize(QtCore.QSize(24, 24))
        self.ImageCapture.setObjectName("ImageCapture")
        self.gridLayout.addWidget(self.ImageCapture, 0, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tittle_bar)
        self.comboBox.setMaximumSize(QtCore.QSize(120, 24))
        self.comboBox.setStyleSheet("background-color: rgb(184, 183, 189);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 5, 1, 1)
        self.horizontalLayout_5.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.restoreButton = QtWidgets.QPushButton(self.top_right_btns)
        self.restoreButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restoreButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon6)
        self.restoreButton.setIconSize(QtCore.QSize(24, 24))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_3.addWidget(self.restoreButton)
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon7)
        self.minimizeButton.setIconSize(QtCore.QSize(24, 24))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon8)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMinimumSize(QtCore.QSize(0, 40))
        self.left_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"background-color:#000;\n"
"}\n"
"\n"
"QPushButton{\n"
"padding:20px 10px;\n"
"border:none;\n"
"border-radius:10px;\n"
"background-color:#000;\n"
"color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.camera_button = QtWidgets.QPushButton(self.left_side_menu)
        self.camera_button.setMinimumSize(QtCore.QSize(100, 62))
        self.camera_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera_button.setStyleSheet("background-image: url(:/icons/icons/cil-video.png);\n"
"background-repeat:none;\n"
"padding-left:50px;\n"
"background-position:center left;")
        self.camera_button.setObjectName("camera_button")
        self.verticalLayout_3.addWidget(self.camera_button)
        self.stage_button = QtWidgets.QPushButton(self.left_side_menu)
        self.stage_button.setMinimumSize(QtCore.QSize(100, 66))
        self.stage_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stage_button.setStyleSheet("background-image: url(:/icons/icons/cil-gamepad.png);\n"
"background-repeat:none;\n"
"padding-left:50px;\n"
"background-position:center left;")
        self.stage_button.setIconSize(QtCore.QSize(16, 16))
        self.stage_button.setObjectName("stage_button")
        self.verticalLayout_3.addWidget(self.stage_button)
        self.laser_button = QtWidgets.QPushButton(self.left_side_menu)
        self.laser_button.setMinimumSize(QtCore.QSize(100, 0))
        self.laser_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.laser_button.setStyleSheet("background-image: url(:/icons/icons/cil-speedometer.png);\n"
"background-repeat:none;\n"
"padding-left:50px;\n"
"background-position:center left;")
        self.laser_button.setIconSize(QtCore.QSize(16, 16))
        self.laser_button.setObjectName("laser_button")
        self.verticalLayout_3.addWidget(self.laser_button)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_items = QtWidgets.QFrame(self.main_body)
        self.center_main_items.setMaximumSize(QtCore.QSize(300, 16777215))
        self.center_main_items.setStyleSheet("")
        self.center_main_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_main_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_items.setObjectName("center_main_items")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.center_main_items)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_items)
        font = QtGui.QFont()
        font.setFamily("Optima")
        font.setItalic(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color:(255,255,255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.camera_page = QtWidgets.QWidget()
        self.camera_page.setObjectName("camera_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.camera_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.camera_page)
        self.frame_3.setStyleSheet("background-color: rgb(196, 196, 200);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.CameraList = QtWidgets.QComboBox(self.frame_9)
        self.CameraList.setMaximumSize(QtCore.QSize(300, 16777215))
        self.CameraList.setObjectName("CameraList")
        self.horizontalLayout_6.addWidget(self.CameraList)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.frequencyList = QtWidgets.QComboBox(self.frame_6)
        self.frequencyList.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frequencyList.setObjectName("frequencyList")
        self.horizontalLayout_14.addWidget(self.frequencyList)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_16.addWidget(self.label_2)
        self.phaseList = QtWidgets.QComboBox(self.frame_8)
        self.phaseList.setObjectName("phaseList")
        self.horizontalLayout_16.addWidget(self.phaseList)
        self.verticalLayout_11.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_17.addWidget(self.label_4)
        self.filtersPositions = QtWidgets.QComboBox(self.frame_10)
        self.filtersPositions.setObjectName("filtersPositions")
        self.horizontalLayout_17.addWidget(self.filtersPositions)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.delayLabel = QtWidgets.QLabel(self.frame_4)
        self.delayLabel.setObjectName("delayLabel")
        self.horizontalLayout_12.addWidget(self.delayLabel)
        self.delayValue = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.delayValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.delayValue.setObjectName("delayValue")
        self.horizontalLayout_12.addWidget(self.delayValue)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.exposureLabel = QtWidgets.QLabel(self.frame_5)
        self.exposureLabel.setObjectName("exposureLabel")
        self.horizontalLayout_13.addWidget(self.exposureLabel)
        self.exposureValue = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.exposureValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.exposureValue.setObjectName("exposureValue")
        self.horizontalLayout_13.addWidget(self.exposureValue)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.SetConfigurationButton = QtWidgets.QPushButton(self.frame_3)
        self.SetConfigurationButton.setObjectName("SetConfigurationButton")
        self.verticalLayout_11.addWidget(self.SetConfigurationButton)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.camera_page)
        self.stages_page = QtWidgets.QWidget()
        self.stages_page.setObjectName("stages_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stages_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.stages_page)
        self.frame.setStyleSheet("background-color: rgb(196, 196, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_10.addWidget(self.comboBox_2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.relativBewegung = QtWidgets.QLineEdit(self.frame_2)
        self.relativBewegung.setMaximumSize(QtCore.QSize(300, 50))
        self.relativBewegung.setObjectName("relativBewegung")
        self.horizontalLayout_11.addWidget(self.relativBewegung)
        self.relativDown = QtWidgets.QPushButton(self.frame_2)
        self.relativDown.setMaximumSize(QtCore.QSize(40, 16777215))
        self.relativDown.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.relativDown.setText("")
        self.relativDown.setIcon(icon7)
        self.relativDown.setObjectName("relativDown")
        self.horizontalLayout_11.addWidget(self.relativDown)
        self.relativUp = QtWidgets.QPushButton(self.frame_2)
        self.relativUp.setMaximumSize(QtCore.QSize(40, 16777215))
        self.relativUp.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.relativUp.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/cil-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.relativUp.setIcon(icon9)
        self.relativUp.setObjectName("relativUp")
        self.horizontalLayout_11.addWidget(self.relativUp)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_10.addWidget(self.doubleSpinBox)
        self.dial = QtWidgets.QDial(self.frame)
        self.dial.setMaximumSize(QtCore.QSize(16777215, 300))
        self.dial.setStyleSheet("color: rgb(170, 0, 0);")
        self.dial.setObjectName("dial")
        self.verticalLayout_10.addWidget(self.dial)
        self.FocusUp_Frame_2 = QtWidgets.QFrame(self.frame)
        self.FocusUp_Frame_2.setMaximumSize(QtCore.QSize(16777215, 37))
        self.FocusUp_Frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FocusUp_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FocusUp_Frame_2.setLineWidth(0)
        self.FocusUp_Frame_2.setObjectName("FocusUp_Frame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.FocusUp_Frame_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.focusUpButton_2 = QtWidgets.QPushButton(self.FocusUp_Frame_2)
        self.focusUpButton_2.setMaximumSize(QtCore.QSize(119, 20))
        self.focusUpButton_2.setObjectName("focusUpButton_2")
        self.horizontalLayout_15.addWidget(self.focusUpButton_2)
        self.focusUp_label_2 = QtWidgets.QLabel(self.FocusUp_Frame_2)
        self.focusUp_label_2.setObjectName("focusUp_label_2")
        self.horizontalLayout_15.addWidget(self.focusUp_label_2)
        self.verticalLayout_10.addWidget(self.FocusUp_Frame_2)
        self.FocusUp_Frame = QtWidgets.QFrame(self.frame)
        self.FocusUp_Frame.setMaximumSize(QtCore.QSize(16777215, 37))
        self.FocusUp_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FocusUp_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FocusUp_Frame.setLineWidth(0)
        self.FocusUp_Frame.setObjectName("FocusUp_Frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.FocusUp_Frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.focusUpButton = QtWidgets.QPushButton(self.FocusUp_Frame)
        self.focusUpButton.setMaximumSize(QtCore.QSize(119, 20))
        self.focusUpButton.setObjectName("focusUpButton")
        self.horizontalLayout_10.addWidget(self.focusUpButton)
        self.focusUp_label = QtWidgets.QLabel(self.FocusUp_Frame)
        self.focusUp_label.setObjectName("focusUp_label")
        self.horizontalLayout_10.addWidget(self.focusUp_label)
        self.verticalLayout_10.addWidget(self.FocusUp_Frame)
        self.FocusDown_Frame = QtWidgets.QFrame(self.frame)
        self.FocusDown_Frame.setMaximumSize(QtCore.QSize(16777215, 37))
        self.FocusDown_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FocusDown_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FocusDown_Frame.setObjectName("FocusDown_Frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.FocusDown_Frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.focusDownButton = QtWidgets.QPushButton(self.FocusDown_Frame)
        self.focusDownButton.setMaximumSize(QtCore.QSize(119, 20))
        self.focusDownButton.setObjectName("focusDownButton")
        self.horizontalLayout_9.addWidget(self.focusDownButton)
        self.focusDown_label = QtWidgets.QLabel(self.FocusDown_Frame)
        self.focusDown_label.setObjectName("focusDown_label")
        self.horizontalLayout_9.addWidget(self.focusDown_label)
        self.verticalLayout_10.addWidget(self.FocusDown_Frame)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 330))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setDigitCount(1)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_10.addWidget(self.lcdNumber)
        self.verticalLayout_6.addWidget(self.frame)
        self.stackedWidget.addWidget(self.stages_page)
        self.laser_page = QtWidgets.QWidget()
        self.laser_page.setStyleSheet("")
        self.laser_page.setObjectName("laser_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.laser_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.laserFrame = QtWidgets.QFrame(self.laser_page)
        self.laserFrame.setStyleSheet("background-color: rgb(196, 196, 200);\n"
"border-color: none;")
        self.laserFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.laserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.laserFrame.setObjectName("laserFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.laserFrame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(63)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.laserFrame)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.laserNavigationBack = QtWidgets.QPushButton(self.frame_7)
        self.laserNavigationBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.laserNavigationBack.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.laserNavigationBack.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-step-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.laserNavigationBack.setIcon(icon10)
        self.laserNavigationBack.setIconSize(QtCore.QSize(24, 24))
        self.laserNavigationBack.setObjectName("laserNavigationBack")
        self.horizontalLayout_8.addWidget(self.laserNavigationBack)
        self.laserLabel = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.laserLabel.setFont(font)
        self.laserLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.laserLabel.setObjectName("laserLabel")
        self.horizontalLayout_8.addWidget(self.laserLabel)
        self.laserNavigationForward = QtWidgets.QPushButton(self.frame_7)
        self.laserNavigationForward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.laserNavigationForward.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.laserNavigationForward.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/cil-media-step-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.laserNavigationForward.setIcon(icon11)
        self.laserNavigationForward.setIconSize(QtCore.QSize(28, 24))
        self.laserNavigationForward.setObjectName("laserNavigationForward")
        self.horizontalLayout_8.addWidget(self.laserNavigationForward)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.circularProgressBar_Main = QtWidgets.QFrame(self.laserFrame)
        self.circularProgressBar_Main.setMaximumSize(QtCore.QSize(327, 248))
        self.circularProgressBar_Main.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBar_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBar_Main.setObjectName("circularProgressBar_Main")
        self.circularProgressCPU = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularProgressCPU.setGeometry(QtCore.QRect(10, 10, 221, 221))
        self.circularProgressCPU.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n"
"}")
        self.circularProgressCPU.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgressCPU.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressCPU.setObjectName("circularProgressCPU")
        self.circularBg = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularBg.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg.setObjectName("circularBg")
        self.circularContainer = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularContainer.setGeometry(QtCore.QRect(25, 25, 190, 190))
        self.circularContainer.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer.setStyleSheet("QFrame{\n"
"    border-radius: 95px;    \n"
"    background-color: rgb(58, 58, 102);\n"
"}")
        self.circularContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer.setObjectName("circularContainer")
        self.layoutWidget = QtWidgets.QWidget(self.circularContainer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 142))
        self.layoutWidget.setObjectName("layoutWidget")
        self.infoLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.infoLayout.setContentsMargins(0, 0, 0, 0)
        self.infoLayout.setObjectName("infoLayout")
        self.wavelengthInfo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.wavelengthInfo.setFont(font)
        self.wavelengthInfo.setStyleSheet("color: #FFFFFF; background-color: none;")
        self.wavelengthInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.wavelengthInfo.setObjectName("wavelengthInfo")
        self.infoLayout.addWidget(self.wavelengthInfo, 0, 0, 1, 1)
        self.laser1_temp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.laser1_temp.setFont(font)
        self.laser1_temp.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.laser1_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.laser1_temp.setObjectName("laser1_temp")
        self.infoLayout.addWidget(self.laser1_temp, 3, 0, 1, 1)
        self.laser1_percentage = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(30)
        self.laser1_percentage.setFont(font)
        self.laser1_percentage.setStyleSheet("color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.laser1_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.laser1_percentage.setIndent(-1)
        self.laser1_percentage.setObjectName("laser1_percentage")
        self.infoLayout.addWidget(self.laser1_percentage, 2, 0, 1, 1)
        self.circularBg.raise_()
        self.circularProgressCPU.raise_()
        self.circularContainer.raise_()
        self.verticalLayout_9.addWidget(self.circularProgressBar_Main)
        self.laserPowerButton = QtWidgets.QPushButton(self.laserFrame)
        self.laserPowerButton.setText("")
        self.laserPowerButton.setObjectName("laserPowerButton")
        self.verticalLayout_9.addWidget(self.laserPowerButton)
        self.laserSlider = QtWidgets.QSlider(self.laserFrame)
        self.laserSlider.setStyleSheet("/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}")
        self.laserSlider.setMaximum(100)
        self.laserSlider.setOrientation(QtCore.Qt.Horizontal)
        self.laserSlider.setObjectName("laserSlider")
        self.verticalLayout_9.addWidget(self.laserSlider)
        self.comboBox_7 = QtWidgets.QComboBox(self.laserFrame)
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_9.addWidget(self.comboBox_7)
        self.comboBox_6 = QtWidgets.QComboBox(self.laserFrame)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_9.addWidget(self.comboBox_6)
        self.verticalLayout_2.addWidget(self.laserFrame)
        self.stackedWidget.addWidget(self.laser_page)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_items)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        self.right_side_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.right_side_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side_menu.setObjectName("right_side_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_side_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.liveViewFrame = QtWidgets.QFrame(self.right_side_menu)
        self.liveViewFrame.setStyleSheet("")
        self.liveViewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liveViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.liveViewFrame.setObjectName("liveViewFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.liveViewFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.graphicsView = plotWidget(self.liveViewFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_8.addWidget(self.graphicsView)
        self.verticalLayout_4.addWidget(self.liveViewFrame)
        self.histogramFrame = QtWidgets.QFrame(self.right_side_menu)
        self.histogramFrame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.histogramFrame.setStyleSheet("")
        self.histogramFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.histogramFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.histogramFrame.setObjectName("histogramFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.histogramFrame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graphicsView_2 = plotWidget(self.histogramFrame)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_7.addWidget(self.graphicsView_2)
        self.verticalLayout_4.addWidget(self.histogramFrame)
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"border-bottom: 1px solid #000;\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Mode"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Intensity"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Color-Mode"))
        self.camera_button.setText(_translate("MainWindow", "CAMERA"))
        self.stage_button.setText(_translate("MainWindow", "STAGES"))
        self.laser_button.setText(_translate("MainWindow", "LASER"))
        self.label_3.setText(_translate("MainWindow", "Select Camera"))
        self.label.setText(_translate("MainWindow", "Frequency "))
        self.label_2.setText(_translate("MainWindow", "Number of Phases "))
        self.label_4.setText(_translate("MainWindow", "Filter Position"))
        self.delayLabel.setText(_translate("MainWindow", "Delay Time "))
        self.exposureLabel.setText(_translate("MainWindow", "exposure Time "))
        self.SetConfigurationButton.setText(_translate("MainWindow", "Set Configuration"))
        self.relativBewegung.setText(_translate("MainWindow", "Please enter the relative value "))
        self.focusUpButton_2.setText(_translate("MainWindow", "Set Auto Focus"))
        self.focusUp_label_2.setText(_translate("MainWindow", "Autofocus inactiv "))
        self.focusUpButton.setText(_translate("MainWindow", "Use as Focus UP"))
        self.focusUp_label.setText(_translate("MainWindow", "Click to store Focus"))
        self.focusDownButton.setText(_translate("MainWindow", "Use as focus Down "))
        self.focusDown_label.setText(_translate("MainWindow", "Click to store Focus"))
        self.laserLabel.setText(_translate("MainWindow", "Laser 1"))
        self.wavelengthInfo.setText(_translate("MainWindow", "<html><head/><body><p>WaveLength = 455mm<br/></p></body></html>"))
        self.laser1_temp.setText(_translate("MainWindow", "<html><head/><body><p>Spec Power: <span style=\" color:#ffffff;\">200 mw</span></p></body></html>"))
        self.laser1_percentage.setText(_translate("MainWindow", "<p align=\"center\"><span style=\" font-size:50pt;\">60</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p>"))

from pyqtgraph import plotWidget
import LSFM_app_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

